print('='*7)
print('TABUADA')
print('='*7)
red = '\033[1;91m'
end = '\033[m'
n = int(input('Escolha um valor para ver a tabuada: '))
print('{} {}X{} 1 = {}{}{}'.format(n, red, end,red, n*1, end))
print('{} {}X{} 2 = {}{}{}'.format(n, red, end, red, n*2, end))
print('{} {}X{} 3 = {}{}{}'.format(n,red, end, red, n*3, end))
print('{} {}X{} 4 = {}{}{}'.format(n, red, end, red, n*4, end))
print('{} {}X{} 5 = {}{}{}'.format(n, red, end, red, n*5, end))
print('{} {}X{} 6 = {}{}{}'.format(n,red, end, red, n*6, end))
print('{} {}X{} 7 = {}{}{}'.format(n, red, end, red, n*7, end))
print('{} {}X{} 8 = {}{}{}'.format(n, red, end, red, n*8, end))
print('{} {}X{} 9 = {}{}{}'.format(n, red, end, red, n*9, end))
print('{} {}X{} 10 = {}{}{}'.format(n, red, end, red, n*10, end))